# Generated by Django 2.1.2 on 2018-11-06 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civility', models.PositiveSmallIntegerField(choices=[(0, 'Monsieur'), (1, 'Madame')], verbose_name='Civilité')),
                ('last_name', models.CharField(max_length=30, verbose_name='Nom')),
                ('first_name', models.CharField(max_length=30, verbose_name='Prénom')),
                ('age', models.PositiveIntegerField(verbose_name='Âge')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('vr', models.BooleanField(default=False, verbose_name='Réalité Virtuelle')),
            ],
            options={
                'verbose_name': 'Jeu',
                'verbose_name_plural': 'Jeux',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=254, verbose_name='Email')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='vdm.Game', verbose_name='Jeu')),
            ],
            options={
                'verbose_name': 'Réservation',
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Créneau',
                'verbose_name_plural': 'Créneaux',
            },
        ),
        migrations.CreateModel(
            name='Spectator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spectateurs', to='vdm.Client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Spectateur',
            },
        ),
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Thème')),
            ],
            options={
                'verbose_name': 'Thème',
            },
        ),
        migrations.AddField(
            model_name='spectator',
            name='tarif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spectateurs', to='vdm.Tarif', verbose_name='Tarif'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='vdm.Slot', verbose_name='Créneau'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='spectators',
            field=models.ManyToManyField(related_name='reservations', to='vdm.Spectator'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='reservation',
            order_with_respect_to='slot',
        ),
    ]
