# Generated by Django 2.1.2 on 2018-11-06 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vdm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemePriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveSmallIntegerField(verbose_name='Priorité')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jeu', to='vdm.Game', verbose_name='Jeu')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='vdm.Theme', verbose_name='Thème')),
            ],
            options={
                'verbose_name': 'Thème avec priorité',
                'verbose_name_plural': 'Thèmes avec priorités',
                'ordering': ('priority',),
            },
        ),
        migrations.AddField(
            model_name='game',
            name='themes',
            field=models.ManyToManyField(related_name='jeux', through='vdm.ThemePriority', to='vdm.Theme', verbose_name='Thème'),
        ),
    ]
