# Generated by Django 2.1.2 on 2018-11-06 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vdm', '0002_auto_20181106_2241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slot',
            options={'ordering': ('time',), 'verbose_name': 'Créneau', 'verbose_name_plural': 'Créneaux'},
        ),
    ]
