# Generated by Django 2.1.2 on 2018-11-07 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdm', '0003_auto_20181106_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarif',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nom'),
        ),
    ]
